name: Publish Website to CPanel
on:
  push:
    branches:
      - main
  jobs:
    FTP-Deploy-Action:
      name: FTP-Deploy-Action
      runs-on: ubuntu-latest
      steps:
      - uses: action/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKrikland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secret.FTP_SERVER }}
          ftp-username: ${{ secret.FTP_USERNAME }}
          ftp-password: ${{ secret.FTP_PASSWORD }}
